GET http://127.0.0.1:3000/item HTTP/1.1

###

GET http://127.0.0.1:3000/item?id=1 HTTP/1.1

###

POST http://127.0.0.1:3000/item HTTP/1.1
content-type: application/json

{}

###

PUT http://127.0.0.1:3000/item HTTP/1.1
content-type: application/json

{}

###

PATCH http://127.0.0.1:3000/item HTTP/1.1
content-type: application/json

{}

###

DELETE http://127.0.0.1:3000/item HTTP/1.1

###

DELETE http://127.0.0.1:3000/item?id=1 HTTP/1.1
